site:
  name: 慧研国际教育
  site: 'https://huiyanedu.com'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId:

metadata:
  title:
    default: 慧研国际教育
    template: '%s | 慧研国际教育'
  description: '慧研国际教育由英国本地硕博导师团队提供留学申请规划、文书辅导、面试准备与落地陪伴服务，强调非流水线、全周期支持。'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: 慧研国际教育
    images: []
    type: website
  twitter:
    handle:
    site:
    cardType: summary_large_image

i18n:
  language: zh-CN
  textDirection: ltr

analytics:
  vendors:
    googleAnalytics:
      id: null

ui:
  theme: 'light:only'
